import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../../models/repair_ticket.dart';
import '../../models/device.dart';
import '../../providers/ticket_provider.dart';
import '../../providers/device_provider.dart';

class CreateTicketScreen extends StatefulWidget {
  final String? deviceId;

  const CreateTicketScreen({
    Key? key,
    this.deviceId,
  }) : super(key: key);

  @override
  State<CreateTicketScreen> createState() => _CreateTicketScreenState();
}

class _CreateTicketScreenState extends State<CreateTicketScreen> {
  final _formKey = GlobalKey<FormState>();
  final _customerNameController = TextEditingController();
  final _customerEmailController = TextEditingController();
  final _customerPhoneController = TextEditingController();
  final _issueDescriptionController = TextEditingController();
  final _estimatedCostController = TextEditingController();

  String? _selectedDeviceId;
  String _selectedDeviceModel = '';
  bool _isSubmitting = false;

  @override
  void initState() {
    super.initState();
    _selectedDeviceId = widget.deviceId;
    
    WidgetsBinding.instance.addPostFrameCallback((_) {
      final deviceProvider = Provider.of<DeviceProvider>(context, listen: false);
      if (deviceProvider.devices.isEmpty) {
        deviceProvider.loadDevices();
      }
      
      if (_selectedDeviceId != null) {
        final device = deviceProvider.getDeviceById(_selectedDeviceId!);
        if (device != null) {
          setState(() {
            _selectedDeviceModel = '${device.manufacturer} ${device.model}';
          });
        }
      }
    });
  }

  @override
  void dispose() {
    _customerNameController.dispose();
    _customerEmailController.dispose();
    _customerPhoneController.dispose();
    _issueDescriptionController.dispose();
    _estimatedCostController.dispose();
    super.dispose();
  }

  Future<void> _submitTicket() async {
    if (!_formKey.currentState!.validate()) {
      return;
    }

    if (_selectedDeviceId == null) {
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: Text('Please select a device'),
          backgroundColor: Colors.red,
        ),
      );
      return;
    }

    setState(() {
      _isSubmitting = true;
    });

    final ticket = RepairTicket(
      id: '', // Will be generated by backend
      customerName: _customerNameController.text.trim(),
      customerEmail: _customerEmailController.text.trim(),
      customerPhone: _customerPhoneController.text.trim(),
      deviceId: _selectedDeviceId!,
      deviceModel: _selectedDeviceModel,
      issueDescription: _issueDescriptionController.text.trim(),
      status: RepairStatus.pending,
      estimatedCost: double.tryParse(_estimatedCostController.text),
      createdAt: DateTime.now(),
      notes: [],
    );

    final ticketProvider = Provider.of<TicketProvider>(context, listen: false);
    final success = await ticketProvider.createTicket(ticket);

    setState(() {
      _isSubmitting = false;
    });

    if (success) {
      if (mounted) {
        Navigator.pop(context);
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Ticket created successfully')),
        );
      }
    } else {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text(ticketProvider.error ?? 'Failed to create ticket'),
            backgroundColor: Colors.red,
          ),
        );
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Create Repair Ticket'),
      ),
      body: Form(
        key: _formKey,
        child: SingleChildScrollView(
          padding: EdgeInsets.all(16),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Card(
                child: Padding(
                  padding: EdgeInsets.all(16),
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Text(
                        'Customer Information',
                        style: Theme.of(context).textTheme.titleLarge,
                      ),
                      SizedBox(height: 16),
                      TextFormField(
                        controller: _customerNameController,
                        decoration: InputDecoration(
                          labelText: 'Customer Name *',
                          prefixIcon: Icon(Icons.person),
                          border: OutlineInputBorder(),
                        ),
                        validator: (value) {
                          if (value == null || value.trim().isEmpty) {
                            return 'Please enter customer name';
                          }
                          return null;
                        },
                      ),
                      SizedBox(height: 16),
                      TextFormField(
                        controller: _customerEmailController,
                        keyboardType: TextInputType.emailAddress,
                        decoration: InputDecoration(
                          labelText: 'Email *',
                          prefixIcon: Icon(Icons.email),
                          border: OutlineInputBorder(),
                        ),
                        validator: (value) {
                          if (value == null || value.trim().isEmpty) {
                            return 'Please enter email';
                          }
                          final emailRegex = RegExp(
                            r'^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$',
                          );
                          if (!emailRegex.hasMatch(value)) {
                            return 'Please enter a valid email';
                          }
                          return null;
                        },
                      ),
                      SizedBox(height: 16),
                      TextFormField(
                        controller: _customerPhoneController,
                        keyboardType: TextInputType.phone,
                        decoration: InputDecoration(
                          labelText: 'Phone Number *',
                          prefixIcon: Icon(Icons.phone),
                          border: OutlineInputBorder(),
                        ),
                        validator: (value) {
                          if (value == null || value.trim().isEmpty) {
                            return 'Please enter phone number';
                          }
                          return null;
                        },
                      ),
                    ],
                  ),
                ),
              ),
              SizedBox(height: 16),
              Card(
                child: Padding(
                  padding: EdgeInsets.all(16),
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Text(
                        'Device Information',
                        style: Theme.of(context).textTheme.titleLarge,
                      ),
                      SizedBox(height: 16),
                      Consumer<DeviceProvider>(
                        builder: (context, deviceProvider, child) {
                          if (deviceProvider.isLoading) {
                            return Center(child: CircularProgressIndicator());
                          }

                          if (deviceProvider.devices.isEmpty) {
                            return Column(
                              children: [
                                Text('No devices available'),
                                SizedBox(height: 8),
                                ElevatedButton(
                                  onPressed: () => deviceProvider.loadDevices(),
                                  child: Text('Reload Devices'),
                                ),
                              ],
                            );
                          }

                          return DropdownButtonFormField<String>(
                            value: _selectedDeviceId,
                            decoration: InputDecoration(
                              labelText: 'Select Device *',
                              prefixIcon: Icon(Icons.phone_android),
                              border: OutlineInputBorder(),
                            ),
                            items: deviceProvider.devices.map((device) {
                              return DropdownMenuItem(
                                value: device.id,
                                child: Text('${device.manufacturer} ${device.model} (${device.serialNumber})'),
                              );
                            }).toList(),
                            onChanged: (value) {
                              if (value != null) {
                                final device = deviceProvider.getDeviceById(value);
                                setState(() {
                                  _selectedDeviceId = value;
                                  _selectedDeviceModel = device != null
                                      ? '${device.manufacturer} ${device.model}'
                                      : '';
                                });
                              }
                            },
                            validator: (value) {
                              if (value == null) {
                                return 'Please select a device';
                              }
                              return null;
                            },
                          );
                        },
                      ),
                      if (_selectedDeviceModel.isNotEmpty) ...[
                        SizedBox(height: 8),
                        Text(
                          'Selected: $_selectedDeviceModel',
                          style: Theme.of(context).textTheme.bodySmall?.copyWith(
                                color: Theme.of(context).colorScheme.primary,
                              ),
                        ),
                      ],
                    ],
                  ),
                ),
              ),
              SizedBox(height: 16),
              Card(
                child: Padding(
                  padding: EdgeInsets.all(16),
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Text(
                        'Repair Details',
                        style: Theme.of(context).textTheme.titleLarge,
                      ),
                      SizedBox(height: 16),
                      TextFormField(
                        controller: _issueDescriptionController,
                        maxLines: 5,
                        decoration: InputDecoration(
                          labelText: 'Issue Description *',
                          hintText: 'Describe the problem in detail...',
                          border: OutlineInputBorder(),
                          alignLabelWithHint: true,
                        ),
                        validator: (value) {
                          if (value == null || value.trim().isEmpty) {
                            return 'Please describe the issue';
                          }
                          if (value.trim().length < 10) {
                            return 'Please provide more details (at least 10 characters)';
                          }
                          return null;
                        },
                      ),
                      SizedBox(height: 16),
                      TextFormField(
                        controller: _estimatedCostController,
                        keyboardType: TextInputType.numberWithOptions(decimal: true),
                        decoration: InputDecoration(
                          labelText: 'Estimated Cost (Optional)',
                          prefixText: '\$ ',
                          prefixIcon: Icon(Icons.attach_money),
                          border: OutlineInputBorder(),
                          hintText: '0.00',
                        ),
                        validator: (value) {
                          if (value != null && value.isNotEmpty) {
                            final cost = double.tryParse(value);
                            if (cost == null || cost < 0) {
                              return 'Please enter a valid cost';
                            }
                          }
                          return null;
                        },
                      ),
                    ],
                  ),
                ),
              ),
              SizedBox(height: 24),
              SizedBox(
                width: double.infinity,
                height: 50,
                child: ElevatedButton(
                  onPressed: _isSubmitting ? null : _submitTicket,
                  child: _isSubmitting
                      ? Row(
                          mainAxisAlignment: MainAxisAlignment.center,
                          children: [
                            SizedBox(
                              width: 20,
                              height: 20,
                              child: CircularProgressIndicator(
                                strokeWidth: 2,
                                valueColor: AlwaysStoppedAnimation<Color>(Colors.white),
                              ),
                            ),
                            SizedBox(width: 12),
                            Text('Creating...'),
                          ],
                        )
                      : Text(
                          'Create Ticket',
                          style: TextStyle(fontSize: 16),
                        ),
                ),
              ),
              SizedBox(height: 8),
              SizedBox(
                width: double.infinity,
                height: 50,
                child: OutlinedButton(
                  onPressed: _isSubmitting ? null : () => Navigator.pop(context),
                  child: Text(
                    'Cancel',
                    style: TextStyle(fontSize: 16),
                  ),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
